# Generated by Django 4.2.4 on 2023-08-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("description", models.TextField(max_length=2048)),
                (
                    "tag_choices",
                    models.CharField(
                        choices=[
                            ("Bug", "Bug"),
                            ("Feature", "Feature"),
                            ("Task", "Task"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority_choices",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status_choices",
                    models.CharField(
                        choices=[
                            ("To do", "To do"),
                            ("In progress", "In progress"),
                            ("Finished", "Finished"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
