# Generated by Django 4.2.3 on 2023-07-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="type_choice",
            field=models.CharField(
                choices=[
                    ("BACK-END", "Back-end"),
                    ("FRONT-END", "Front-end"),
                    ("IOS", "iOS"),
                    ("ANDROID", "Android"),
                ],
                max_length=20,
            ),
        ),
    ]
