# Generated by Django 4.2.3 on 2023-07-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("issues", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=2048)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "author_user",
                    models.OneToOneField(
                        on_delete=models.SET("auth.User"), to="users.user"
                    ),
                ),
                (
                    "issue",
                    models.OneToOneField(
                        on_delete=models.SET("auth.User"), to="issues.issue"
                    ),
                ),
            ],
            options={
                "ordering": ["created_datetime"],
            },
        ),
    ]
