# Generated by Django 4.2.4 on 2023-08-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[("AUTHOR", "Author"), ("CONTRIBUTORS", "Contributor")],
                        max_length=20,
                    ),
                ),
                ("role", models.CharField(max_length=100)),
            ],
        ),
    ]
